name: Publish

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.9
        with:
          python_version: "3.10.1"
          poetry_version: "1.1.12"
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
